before:
  hooks:
    - go mod tidy

builds:

- main: main.go
  binary: golem
  id: golem

  env:
  - CGO_ENABLED=0

  goos: [windows,linux,darwin]
  goarch: [amd64,386,arm,arm64]
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

  flags:
    - -trimpath

dockers:
- image_templates: ["4nth0/golem:{{ .Tag }}"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--build-arg=GIT_TAG_NAME={{ .Tag }}"

archives:
- format: zip
  id: golem
  builds: [golem]
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256
